### ISSUE TITLE
Question about Table 5 in the paper

### ISSUE THREAD

**Issue by zhezh** [zdou0830/METER#1]
Hi, 
as stated in the first row of table 5, 
the TR for Flickr-ZS is 90.38 which is highest among the column but not in bold.
Is this a lapse or the real result ?

By the way, in my understanding, the text embedding in `emb-only` method is obtained from BERT embedding module without encoder module, it contains no contextual information. Do I understand it correctly?

**Comment by zdou0830** [comment]
Hi, the TR for Flickr-ZS should be 74.10, thanks for catching this error! And yes, your understanding is correct.
