### ISSUE TITLE
SNLI dataset download

### ISSUE THREAD

**Issue by jiyt17** [zdou0830/METER#10]
Hello~ In VILT github repo, there is no snli dataset download and deal details. So is there any snli dataset preperation guideline?

**Comment by zdou0830** [comment]
Hi, you'll first need to generate the raw data following https://github.com/necla-ml/SNLI-VE.

Then, you can run the following command to generate the `pyarrow` file:
```
from meter.utils.write_snli import make_arrow
make_arrow('SNLI-VE/data', arrows_root)
```

**Comment by jiyt17** [comment]
ok， thank u~
