### ISSUE TITLE
question about whole_work_mask

### ISSUE THREAD

**Issue by qizhust** [zdou0830/METER#14]
Hi, it seems that whole_word_mask is unsuitable for roberta, yet in your example script
```
python run.py with data_root=/data2/dsets/dataset num_gpus=8 num_nodes=1 task_mlm_itm_clip_bert per_gpu_batchsize=32 clip16 text_roberta image_size=288
```
I wonder whether there is performance drop when setting whole_word_mask=True for text_roberta.

**Comment by zdou0830** [comment]
Hi, I had noted this here https://github.com/zdou0830/METER/blob/main/meter/config.py#L44 and I didn't see any performance drop.
