### ISSUE TITLE
GPU OOM when pretraining

### ISSUE THREAD

**Issue by hi-zhenyu** [zdou0830/METER#16]
HI, I'm trying to pre-train the METER  by using 8 A100 GPUS with the recommended config:
```
python run.py with num_gpus=8 num_nodes=1 task_mlm_itm_clip_bert per_gpu_batchsize=32 clip16 text_roberta image_size=288
```
but the GPU OOM occurred. 

So what is the extract per_gpu_batchsize? And how can I pre-train the model in about 8 days as mentioned in the paper.

By the way, will the mixed precision training (precision=16) cause a performance drop?

Many thanks!

**Comment by zdou0830** [comment]
Hello, you may need to tune `per_gpu_batch_size` based on your GPUs.

I set `precision` to 32 because using mixed-precision training can sometimes cause the NaN issue.

**Comment by hi-zhenyu** [comment]
Hi, thanks for your reply.

In the paper, you said it takes around 8 days for METER-SwinBASE and METER-CLIP-ViTBASE−16 for training 100k steps on 8 A100 GPUs. However, in my experiments, it obviously needs more time for training, especially the per_gpu_batch_size need to be reduced due to the OOM problem (<32).

So could you please give me some advice to speed up training like the paper statement (~8 days with 8 A100 GPUs).

**Comment by zdou0830** [comment]
Hi, I think you can try reducing the GPU memory usage by setting the precision to 16, using a smaller max_text_len, etc. Training the models for ~50k steps should also give you a decent performance.

**Comment by mactavish91** [comment]
> Hi, thanks for your reply.
> 
> In the paper, you said it takes around 8 days for METER-SwinBASE and METER-CLIP-ViTBASE−16 for training 100k steps on 8 A100 GPUs. However, in my experiments, it obviously needs more time for training, especially the per_gpu_batch_size need to be reduced due to the OOM problem (<32).
> 
> So could you please give me some advice to speed up training like the paper statement (~8 days with 8 A100 GPUs).

@hi-zhenyu Hello, have you solved the problems you encountered before?
