### ISSUE TITLE
What's the definition of cls_feats in the code?

### ISSUE THREAD

**Issue by applenob** [zdou0830/METER#2]
![image](https://user-images.githubusercontent.com/5762816/143195009-8c2f93be-8878-41de-8c1f-85536b4dc7cf.png)

In the function `METERTransformerSS.infer`, seems no definition of `cls_feats`. Is `cls_feats ` combined from `cls_feats_text` and `cls_feats_image`?

https://github.com/zdou0830/METER/blob/3531ca21180ac0fb641f61964a795ba816f71ca0/meter/modules/meter_module.py?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L230

**Comment by zdou0830** [comment]
Hi, we will update the code and release the models by the end of this week, please stay tuned, thanks!
