### ISSUE TITLE
question about the pre-trained weights

### ISSUE THREAD

**Issue by Junction4Nako** [zdou0830/METER#20]
Dear authors,
    Thanks for the great work! I have downloaded the pre-trained weights of ViT-B-16(224)+RoBERTa checkpoint from https://github.com/zdou0830/METER/releases/download/checkpoint2/meter_clip16_224_roberta_pretrain.ckpt, and found that the last layer of the visual encoder "vit_model.visual.transformer.resblocks.11..." is not included in the ckpt file? Did I miss something? Could you please help me to check it?

**Comment by zdou0830** [comment]
Hi, we removed the last layer of CLIP (https://github.com/zdou0830/METER/issues/9) because it is essentially a pooling layer and we found that removing it could lead to small improvements.

**Comment by Junction4Nako** [comment]
> Hi, we removed the last layer of CLIP (#9) because it is essentially a pooling layer and we found that removing it could lead to small improvements.

many thanks for your reply~
