### ISSUE TITLE
questions about vqa

### ISSUE THREAD

**Issue by qizhust** [zdou0830/METER#23]
Hi, what the image_size used for VQAv2 in Table 2 and Table 3 in your paper?

**Comment by zdou0830** [comment]
Hi, as in the paper, the image size is 224×224 or 384×384 depending on the adopted vision transformers. For example, CLIP-224/32 and CLIP-224/16 used an image size of 224x224, Swin32_base384 used 384x384

**Comment by qizhust** [comment]
Thanks!
