### ISSUE TITLE
The config setting of swin transformer

### ISSUE THREAD

**Issue by jiyt17** [zdou0830/METER#3]
hello, thanks for your open code of METER, which has many valuable experiments.
The code uses clip-vit to extract visual features. If I want to utilize swin transformer, what configs should I set? Thank you again~

**Comment by zdou0830** [comment]
Hi, you can add `swin32_base384` to the command. The details can be seen in this file https://github.com/zdou0830/METER/blob/main/meter/config.py.

**Comment by jiyt17** [comment]
thank you!
