### ISSUE TITLE
Unable to train models faster with more gpus

### ISSUE THREAD

**Issue by HarmanDotpy** [zdou0830/METER#30]
Hi,
I am facing an issue where, on increasing the number of gpus and nodes, the number of steps for each epoch doesnot change. for eg if I run

`python run.py with data_root=/data/datasets/meter_data_combined num_gpus=4 num_nodes=8 task_mlm_itm_clip_bert per_gpu_batchsize=64 clip16 text_roberta image_size=224 precision=16 datasets='["vg"]'`

the number of steps per epoch is nearly 150k. I observe that the number of steps is 150k when num_gpus=1 num_nodes=1, and when num_gpus=4 num_nodes=8. I made sure that all gpus were being utilized when I set num_gpus=4 num_nodes=8. I also observe that while using num_gpus=4 num_nodes=8, the time for each epoch is ~160 hours in my case, while it is ~30 hours if I set num_gpus=1 num_nodes=1. 

Is there any suggestion that you have for this problem?

**Comment by zdou0830** [comment]
Hi, I suspect this is a distributed training problem and you can try to compare (num_gpus=4, num_nodes=1) and (num_gpus=1, num_nodes=1) to see if this is true. I used this script https://github.com/zdou0830/METER/blob/main/azure_distributed_run.py when running on multiple nodes on Microsoft machines and you may adapt it based on your environment.

**Comment by HarmanDotpy** [comment]
Thanks, 
I found the problem, that I had commented out the distributed sampler part in the lightbingdatamodule.
I had done this because, i had read that lightning should be able to do distributedsampling automatically (atleast in the new lightning version I am using). However, it seems like if I remove the distributed sampler, it doesn't work.
Any idea why this would be happening?

**Comment by zdou0830** [comment]
Hi, I'm not sure about how lightning automatically does distributedsampling. METER used lightning 1.3.2 and you can refer to their document.
