### ISSUE TITLE
pretraining task

### ISSUE THREAD

**Issue by mactavish91** [zdou0830/METER#31]
Hello, the author, great work! I'm curious whether you have tried to add Image Text Contrast Learning in the pretraining task? Because in the ALBEF paper, they reported that the ITC task had a great impact on the experimental results.

**Comment by zdou0830** [comment]
Hello, we tried ITC in our follow-up work FIBER (https://arxiv.org/abs/2206.07643) and you can see the ablation study in the appendix.

**Comment by mactavish91** [comment]
> Hello, we tried ITC in our follow-up work FIBER (https://arxiv.org/abs/2206.07643) and you can see the ablation study in the appendix.

@zdou0830 Thank you for your kindly help, could you tell me when will the code for FIBER be publicly available?

**Comment by zdou0830** [comment]
Hi, the code was taken down due to an internal issue and they will re-publicize it once the issue is resolved.

**Comment by zdou0830** [comment]
the FIBER repo has been re-publicized now https://github.com/microsoft/FIBER
