### ISSUE TITLE
Image Caption Script

### ISSUE THREAD

**Issue by Markin-Wang** [zdou0830/METER#32]
Hi author, thanks for your work. Can you provide an example script for the image caption downstream task?

Thanks.

**Comment by FerryHuang** [comment]
Hello, you may check 'Evaluation on Downstream Tasks' in README.md and find whether it's what you want?
![image](https://user-images.githubusercontent.com/71176040/201471719-fc32a022-201d-4c9d-acee-03d39451da56.png)

**Comment by Markin-Wang** [comment]
> Hello, you may check 'Evaluation on Downstream Tasks' in README.md and find whether it's what you want? ![image](https://user-images.githubusercontent.com/71176040/201471719-fc32a022-201d-4c9d-acee-03d39451da56.png)

Hi Ferry,
Thank you so much for your reply. Sorry that I didn't explain clearly about the task. 
The image caption task is the task mentioned in your supplementary file, where the evaluation metrics are BLEU, METEOR, Cider and SPICE.
In addition, may I ask about the decoder experiments as I cannot see the setting of adding the optinal decoder.
Thanks for your kind help.

**Comment by FerryHuang** [comment]
> > Hello, you may check 'Evaluation on Downstream Tasks' in README.md and find whether it's what you want? ![image](https://user-images.githubusercontent.com/71176040/201471719-fc32a022-201d-4c9d-acee-03d39451da56.png)
> 
> Hi Ferry, Thank you so much for your reply. Sorry that I didn't explain clearly about the task. The image caption task is the task mentioned in your supplementary file, where the evaluation metrics are BLEU, METEOR, Cider and SPICE. In addition, may I ask about the decoder experiments as I cannot see the setting of adding the optinal decoder. Thanks for your kind help.

I should be sorry that I actually mistake this as script for image caption task which is indeed for image/text retrieval. I'll delete my reply...Plus, I am also trying to apply an additional decoder (author seems to leave this for future work) as to applying model on image caption :)

**Comment by Markin-Wang** [comment]
> 

Hhaha, Never mind.
In the paper, the authors compare the performance with and without the decoder. Also, they verify their model on image caption task.
Therefore, I guess there is an implementation for the relevant parts and ask for the script and details, e.g., the implementation details of the decoder.

Maybe we can have more discussion later.
Thanks for your kind information.

**Comment by zdou0830** [comment]
Hello, you can find the image captioning code in our new FIBER repo https://github.com/microsoft/FIBER/

**Comment by Markin-Wang** [comment]
> Hello, you can find the image captioning code in our new FIBER repo https://github.com/microsoft/FIBER/

Thanks for your reply. I will take a look. Again, thanks for sharing the code.
