### ISSUE TITLE
MLM task without visual input

### ISSUE THREAD

**Issue by qizhust** [zdou0830/METER#5]
Hi, thanks for the code! According to your paper, the model is trained to reconstruct the original tokens given the
masked tokens and its corresponding visual input v in MLM. However, in the compute_mlm() function, the prediction is not conditioned on visual inputs. I wonder whether the visual input can help the pretraining.

**Comment by zdou0830** [comment]
Hello, the prediction is indeed conditioned on visual inputs. We didn't try MLM without visual inputs.

**Comment by qizhust** [comment]
You're right, thanks!
