### ISSUE TITLE
result difference

### ISSUE THREAD

**Issue by qizhust** [zdou0830/METER#6]
Hi, could you explain what is the difference between the 'RoBERTa-CLIP-16' in Table 4 and the 'METER-CLIP-ViT_BASE' in Table 7?

**Comment by zdou0830** [comment]
Hello, in Table 4, the image resolution during pre-training is set to 224x224, but in Table 7 it is 288x288 as in the paper.

**Comment by qizhust** [comment]
Got it, thanks!
