### ISSUE TITLE
CLIP - omitted last layer

### ISSUE THREAD

**Issue by eladsegal** [zdou0830/METER#9]
Hi,
I've noticed that the CLIP model uses only 11 layers instead of 12, omitting the last layer.
https://github.com/zdou0830/METER/blob/03e904c876418d8273b443bbf1ee48422ca7ea4b/meter/modules/clip_model.py#L55

The original CLIP code:
https://github.com/openai/CLIP/blob/573315e83f07b53a61ff5098757e8fc885f1703e/clip/model.py#L196

Is there a reason for this?

**Comment by zdou0830** [comment]
Hi, we found that using 11 layers is slightly better (~0.5 improvements in VQA scores).

**Comment by eladsegal** [comment]
Thank you!
